mavve/src/components/RoomPage/RoomDeleteModal.jsx
mavve/src/components/RoomPage/RoomInfoHeader.jsx
mavve/src/pages/RoomPage/RoomPage.jsx
mavve/src/pages/RoomPage/RoomPage.style.js

- 피그마에 추가된 방 삭제 버튼 및 모달을 만들었습니당 
---
-closes(#14)
---
.
---

✨방 삭제 버튼 및 모달 추가 

---

mavve/package.json
mavve/src/App.jsx
mavve/src/api/axiosInstance.js
mavve/src/api/image.js
mavve/src/api/room.js
mavve/src/components/RoomPage/ConfirmedPlaylistView.jsx
mavve/src/components/RoomPage/PlayListSelector.jsx
mavve/src/components/RoomPage/RoomCreateForm.jsx
mavve/src/components/RoomPage/RoomDeleteModal.jsx
mavve/src/components/RoomPage/RoomInfoHeader.jsx
mavve/src/pages/RoomPage/RoomPage.jsx
mavve/src/pages/RoomPage/RoomPage.style.js
mavve/yarn.lock

방 생성, 삭제, 수정 API를 연결했습니다 
---
- 관련 이슈: #22 
---
- 플레이리스트 추가하는 부분은 playlist 관련 api 먼저 연결되어야 할 것 같아서 비워놓았습니다 
---

✨ 방 생성/삭제/수정 API 연결

---

mavve/package.json
mavve/src/App.jsx
mavve/src/api/chat.js
mavve/src/api/client.js
mavve/src/api/room.js
mavve/src/components/RoomInsidePage/FriendsModal.jsx
mavve/src/components/RoomInsidePage/RoomChat.jsx
mavve/src/components/RoomInsidePage/RoomPlayList.jsx
mavve/src/components/RoomInsidePage/SongAddModal.jsx
mavve/src/components/RoomPage/RoomInfoHeader.jsx
mavve/src/pages/RoomInsidePage/RoomInsidePage.jsx
mavve/src/pages/RoomInsidePage/RoomInsidePage.style.js
mavve/src/pages/RoomPage/RoomPage.style.js
mavve/yarn.lock

- 방 생성 후 입장하기 버튼 누르면 생성된 방 내부 페이지로 연결됨
- 채팅 브로드캐스트 수신, 채팅 생성
- 새 채팅 입력하면 맨 밑으로 자동스크롤
---
- 관련 이슈: #27 
---
---
https://github.com/user-attachments/assets/de543415-b729-4c55-915c-c4d28ffea51a

✨ 방 입장/채팅 웹소켓 연결 

---

mavve/src/api/diary.js
mavve/src/api/image.js
mavve/src/api/room.js
mavve/src/api/song.js
mavve/src/api/user.js
mavve/src/assets/MyPage/MinusIcon.svg
mavve/src/components/Common/OneLineNote.jsx
mavve/src/components/Common/OneLineNote.style.js
mavve/src/components/Common/RoomComponent.jsx
mavve/src/components/Common/RoomComponent.style.js
mavve/src/components/MainPage/Diaries.jsx
mavve/src/components/MyPage/EmojiSelectModal.jsx
mavve/src/components/MyPage/MusicSelectModal.jsx
mavve/src/components/MyPage/OneLineNoteModal.jsx
mavve/src/components/MyPage/Profile.jsx
mavve/src/components/MyPage/ProfileEditModal.jsx
mavve/src/components/MyPage/ProfileEditModal.style.js
mavve/src/pages/MyPage/MyPage.jsx
mavve/src/pages/MyPage/MyPage.style.js
mavve/src/pages/MyPage/MyRoomPage.jsx

- MyPage의 프로필, 한 줄 일기, 내가 만든 방 API를 연결하였습니다.
---
- 관련 이슈: #26 
---
-  방 좋아요와 좋아요한 방은 아직 API 구현되지 않았습니다.
- 방 클릭 시 이동은 적용되지 않은 상태입니다.
---
>

✨MyPage API(프로필, 한 줄 일기, 내가 만든 방) 연결

---

mavve/src/api/room.js
mavve/src/components/Common/RoomComponent.jsx
mavve/src/components/Common/RoomComponent.style.js
mavve/src/components/MyPage/MusicSelectModal.jsx
mavve/src/components/MyPage/OneLineNoteModal.jsx
mavve/src/components/MyPage/Profile.jsx
mavve/src/components/MyPage/ProfileEditModal.style.js
mavve/src/pages/MyPage/LikedRoomPage.jsx
mavve/src/pages/MyPage/MyPage.jsx
mavve/src/pages/MyPage/MyRoomPage.jsx

MyPage의 좋아요 관련 API를 연결하였습니다. 
- 방 좋아요
- 좋아요한 방 리스트
- 내가 만든 방, 좋아요한 방 상세 페이지
- 프로필  영역에 표시되는 '내가 만든 방 개수'가 반영되도록 업데이트 하였습니다. 
---
- 관련 이슈: #36 
---
- 방 컴포넌트의 hover, click 시의 스타일링은 이후 추가 예정입니다. 
---
> https://github.com/user-attachments/assets/7af5b2b0-e3e2-450d-9c96-311ca964593a

✨MyPage 좋아요, 좋아요한 방 API 연결

---

mavve/src/components/Common/RoomComponent.jsx

- develop 브랜치 확인해보니 방 입장 경로가 바뀌어서 해당 코드에 맞게 수정하였습니다. 
---
- 관련 이슈: #36 
---
-

🩹 방 클릭 입장 경로 수정

---

mavve/src/components/RoomInsidePage/RoomChat.jsx

- 채팅이 한번에 15개만 보이는데, 스크롤을 올리면 이전 채팅도 15개씩 보이도록 수정하였습니당. 
---
- 관련 이슈: #29 
---
---

🐛 채팅 무한 스크롤 구현

---

mavve/src/components/RoomPage/PlayListSelector.jsx

플레이리스트 검색 시 duration, 곡수 추가 
---
- 관련 이슈: #61 
---
---

🐛 방 생성시 플레이리스트 검색 수정

---

mavve/src/api/auth.js
mavve/src/api/room.js
mavve/src/api/user.js
mavve/src/components/Common/Menu.jsx
mavve/src/components/Common/OneLineNote.style.js
mavve/src/components/Common/RoomSearch.jsx
mavve/src/components/Common/RoomSearch.style.js
mavve/src/components/Common/TopBar.jsx
mavve/src/components/MyPage/ProfileEditModal.jsx
mavve/src/pages/LoginPage/LoginLoadPage.jsx

- GNB의 방 검색 API 연결
- 로그아웃 API 연결
- 결과 창 좋아요 기능 추가
---
- 관련 이슈: #55 
---
- 경로 수정은 머지 이후 다시 할 예정입니다.
- 로그아웃 이후 정보가 없어서 에러가 뜨는 경우는 확인하는 대로 수정 중입니다!!
---
><img width="1454" height="754" alt="image" src="https://github.com/user-attachments/assets/a49d2c41-022a-41ce-8d68-43657056e90e" />

✨GNB 방 검색, 로그아웃 API 연결, 결과 창 좋아요 기능 추가

---

mavve/src/components/RoomPage/RoomCreateForm.jsx
mavve/src/pages/RoomPage/RoomPage.jsx

- 해시태그가 두번씩 입력되거나 엔터를 쳐도 입력이 안되는 문제를 수정하였습니다 
---
- 관련 이슈: #70 
---
---

🐛 해시태그 입력 오류 수정

---

mavve/src/components/RoomPage/ConfirmedPlaylistView.jsx
mavve/src/components/RoomPage/RoomInfoHeader.jsx
mavve/src/pages/RoomPage/RoomPage.jsx
mavve/src/pages/RoomPage/RoomPage.style.js

- 방 생성 화면에서 곡수, 시간 및 세부 UI를 수정했습니다 
---
- 관련 이슈: #75 
---
---

🐛 방 곡수, 시간 표시 수정

---

mavve/src/components/RoomInsidePage/RoomPlayList.jsx
mavve/src/pages/RoomInsidePage/RoomInsidePage.jsx

- 노래가 추가/삭제된 다음에는 방 내부 상단의 총 곡수, duration이 수정되도록 하였습니당 
---
---
---

🐛 방 내부 상단 표시 수정

---

mavve/src/pages/RoomInsidePage/RoomInsidePage.jsx

- 새로고침 후에도 유지되는 localStorage만 신뢰하도록 수정
---
- 관련 이슈: #78 
---
---

🐛 새로고침 재생 에러 방지

---

mavve/src/components/RoomInsidePage/RoomPlayList.jsx

- 방 내부 좋아요 추가 
---
- 관련 이슈: #63 
---
---

✨ 방 내부 좋아요 연결 

---

mavve/src/components/Common/RoomComponent.jsx
mavve/src/components/Common/RoomSearch.jsx

- 마이페이지, 검색창에서 방 내부로 이동하는 경로 수정 
---
- 관련 이슈: #87 
---
---

🐛 방 이동 경로 수정

---

mavve/src/api/room.js
mavve/src/components/MainPage/TopFiveRoom.jsx
mavve/src/components/MainPage/TopFiveRoom.style.js

- 메인페이지 Top5 방 컴포넌트 API 연결사항 수정
---
- 관련 이슈: #91 
---
- 없습니다.
---

메인페이지 Top5방 API 연결 수정

---

mavve/src/components/Common/RoomComponent.style.js

- 방 해시태그 위치 수정
- 방 호버링, 클릭 스타일 적용
---
- 관련 이슈: #95 
---
- 추후 디자이너 요청 시 수정 가능
---

💄 방 컴포넌트 스타일 수정

---

mavve/src/App.jsx
mavve/src/hoc/Auth.jsx

- auth HOC 설정
---
- 관련 이슈: #97 
---
- 현재는 닉네임으로 로그인 여부 판단 중입니다. 사용자 닉네임이 null로 설정될 수 없는 상태라서 우선 그렇게 하고 있습니다! 
---

✨ auth HOC 설정

---

mavve/src/components/Common/SideBar.jsx
mavve/src/pages/MyPage/MyPage.jsx
mavve/src/pages/MyPage/MyPage.style.js
mavve/src/pages/PlaylistPage/NewPlaylistPage.style.js
mavve/src/pages/PlaylistPage/PlaylistDetailPage.style.js
mavve/src/pages/PlaylistPage/PlaylistPage.style.js
mavve/src/pages/RoomPage/RoomPage.style.js

- 페이지간 레이아웃이나 간격이 조금씩 안 맞는 것들을 수정하였습니당 
---
- 관련 이슈: #124 
---
---

💄 전체 페이지 레이아웃 재수정

---

mavve/src/api/chat.js
mavve/src/pages/RoomInsidePage/RoomInsidePage.jsx

- 방 내부에서 방 검색을 통해 다른 방으로 이동할 때, 웹소켓을 해제하기 전에 연결하려고 해서 오류가 생기는 점을 해결했습니다! 
---
- 관련 이슈: #127 
---
---

🐛 방 내부 이동 오류 수정

---

mavve/src/components/MyPage/Profile.jsx
mavve/src/pages/MyPage/MyPage.jsx

- 프로필 내의 플레이리스트 개수 반영
---
- 관련 이슈: #123 
---
---

🐛 프로필 플레이리스트 개수 반영

---

mavve/src/pages/MyPage/MyPage.style.js
mavve/src/pages/MyPage/MyRoomPage.jsx

- 내가 만든 방 내부 컨텍스트 메뉴 추가
---
- 관련 이슈: #131

🐛 내가 만든 방 내부 컨텍스트 메뉴 추가

---

mavve/src/pages/RoomInsidePage/RoomInsidePage.jsx

- 확인 결과 노래 재생 seekPosition에 오류가 있어 다시 수정했습니다 
---
- 관련 이슈: #134 
---
---

🐛 방 내부 곡 재생 불일치 수정
